CREATE TABLE IF NOT EXISTS DIM_DATES_DAY (
    -- Surrogate key (YYYYMMDD)
    DATE_ID        INT         NOT NULL PRIMARY KEY,
    DAY            SMALLINT    NOT NULL, 
    DAY_OF_WEEK    SMALLINT    NOT NULL,  
    DAY_NAME       VARCHAR(20) NOT NULL, 
    WEEK           SMALLINT    NOT NULL,  
    WEEK_OF_YEAR   SMALLINT    NOT NULL,  
    MONTH          SMALLINT    NOT NULL,  
    MONTH_NAME     VARCHAR(20) NOT NULL,  
    QUARTER        SMALLINT    NOT NULL,  
    YEAR           SMALLINT    NOT NULL,  
    IS_WEEKEND     BOOLEAN     NOT NULL,

   
    CONSTRAINT CHK_DIM_DATES_DAY        CHECK (DAY BETWEEN 1 AND 31),
    CONSTRAINT CHK_DIM_DATES_DOW        CHECK (DAY_OF_WEEK BETWEEN 1 AND 7),
    CONSTRAINT CHK_DIM_DATES_WEEK       CHECK (WEEK BETWEEN 1 AND 53),
    CONSTRAINT CHK_DIM_DATES_WOY        CHECK (WEEK_OF_YEAR BETWEEN 1 AND 53),
    CONSTRAINT CHK_DIM_DATES_MONTH      CHECK (MONTH BETWEEN 1 AND 12),
    CONSTRAINT CHK_DIM_DATES_QUARTER    CHECK (QUARTER BETWEEN 1 AND 4),
    CONSTRAINT CHK_DIM_DATES_YEAR       CHECK (YEAR BETWEEN 1900 AND 2100),
    CONSTRAINT CHK_DIM_DATES_DATE_ID    CHECK (DATE_ID BETWEEN 19000101 AND 21001231)
);


INSERT INTO DIM_DATES_DAY (
    DATE_ID, DAY, DAY_OF_WEEK, DAY_NAME,
    WEEK, WEEK_OF_YEAR, MONTH, MONTH_NAME,
    QUARTER, YEAR, IS_WEEKEND
)
SELECT *
FROM (
    SELECT
        (EXTRACT(YEAR  FROM d)::INT * 10000 +
         EXTRACT(MONTH FROM d)::INT * 100 +
         EXTRACT(DAY   FROM d)::INT)          AS DATE_ID,
        EXTRACT(DAY FROM d)::SMALLINT         AS DAY,
        EXTRACT(ISODOW FROM d)::SMALLINT      AS DAY_OF_WEEK,
        TRIM(TO_CHAR(d, 'Day'))               AS DAY_NAME,
        EXTRACT(WEEK FROM d)::SMALLINT        AS WEEK,
        EXTRACT(WEEK FROM d)::SMALLINT        AS WEEK_OF_YEAR,
        EXTRACT(MONTH FROM d)::SMALLINT       AS MONTH,
        TRIM(TO_CHAR(d, 'Month'))             AS MONTH_NAME,
        EXTRACT(QUARTER FROM d)::SMALLINT     AS QUARTER,
        EXTRACT(YEAR FROM d)::SMALLINT        AS YEAR,
        (EXTRACT(ISODOW FROM d) IN (6,7))     AS IS_WEEKEND
    FROM generate_series(DATE '2020-01-01', DATE '2025-12-31', INTERVAL '1 day') AS d
) s
WHERE NOT EXISTS (
    SELECT 1 FROM DIM_DATES_DAY t WHERE t.DATE_ID = s.DATE_ID
);
--CHECK DUBLICATES
SELECT DATE_ID, COUNT(*)
FROM DIM_DATES_DAY
GROUP BY DATE_ID
HAVING COUNT(*) > 1;


